- name: Activate image and reload (master only if stack)
  delegate_to: localhost
  ansible.builtin.shell: |
    printf "enable\nterminal length 0\nboot system flash:{{ image_file }}\nreload\ny\n" | \
    sshpass -p "{{ ansible_password }}" \
    ssh -tt \
    -o StrictHostKeyChecking=no \
    -o UserKnownHostsFile=/dev/null \
    -o PreferredAuthentications=password \
    -o PubkeyAuthentication=no \
    {{ ansible_user }}@{{ ansible_host }}
  args:
    executable: /bin/bash
  when: not stack.enabled or is_stack_master
