- name: Install image
  ansible.builtin.shell: |
    sshpass -p "{{ ansible_password }}" ssh -tt \
    -o StrictHostKeyChecking=no \
    -o UserKnownHostsFile=/dev/null \
    {{ ansible_user }}@{{ ansible_host }} << 'EOF'
    enable
    boot system image {{ image.filename }}
    write memory
    reload
    EOF
