- name: Save config and reload Netgear switch
  delegate_to: localhost
  ansible.builtin.shell: |
    /usr/bin/expect << 'EOF'
    set timeout 300

    spawn sshpass -p "{{ ansible_password }}" ssh -tt \
      -o StrictHostKeyChecking=no \
      -o UserKnownHostsFile=/dev/null \
      -o PreferredAuthentications=password \
      -o PubkeyAuthentication=no \
      {{ ansible_user }}@{{ ansible_host }}

    expect ">"
    send "enable\r"

    expect "#"
    send "boot system {{ boot_image}} \r"
 
    expect "#"
    send "write memory\r"

    expect {
      "Are you sure you want to save?" {
        send "y\r"
      }
    }

    expect "#"
    send "reload\r"

    expect {
      "Are you sure you want to reload" {
        send "y\r"
      }
    }

    # switch will drop SSH here
    expect eof
    EOF
  args:
    executable: /bin/bash
  register: reload_out
  changed_when: true
  when:
    - not stack.enabled or is_stack_master
