---
- name: Detect stack status
  ansible.builtin.shell: |
    sshpass -p "{{ ansible_password }}" \
    ssh -tt \
    -o StrictHostKeyChecking=no \
    -o UserKnownHostsFile=/dev/null \
    -o PreferredAuthentications=password \
    -o PubkeyAuthentication=no \
    {{ ansible_user }}@{{ ansible_host }} << 'EOF'
    enable
    configure
    show stack-status
    exit
    exit
    EOF
  args:
    executable: /bin/bash
  register: stack_show
  changed_when: false

- name: Determine if stacking already configured
  set_fact:
    stack_configured: "{{ 'Up' in stack_show.stdout }}"

- name: Detect master switch
  set_fact:
    is_stack_master: "{{ inventory_hostname == groups['m4350_stack'][0] }}"

# --------------------------------------------------
# REMOVE AUTO-LAG AND CONFIGURE STACK
# --------------------------------------------------
- name: Configure stack members, priority and ports

  ansible.builtin.template:
    src: stack.j2
    dest: /tmp/{{ inventory_hostname }}_stack.cli
    mode: "0600"
  when:
    - stack.enabled
    - not stack_configured

- name: Apply stack configuration
  ansible.builtin.shell: |
    sshpass -p "{{ ansible_password }}" \
    ssh -T \
        -o StrictHostKeyChecking=no \
        -o UserKnownHostsFile=/dev/null \
        {{ ansible_user }}@{{ ansible_host }} \
        < /tmp/{{ inventory_hostname }}_stack.cli
  when:
    - stack.enabled
    - not stack_configured

- name: Pause briefly before polling for SSH
  pause:
    seconds: 60
  when:
    - stack.enabled
    - not stack_configured
# --------------------------------------------------
# REBOOT STACK (REQUIRED)
# --------------------------------------------------
- name: Reload stack (confirm yes)
  shell: |
    sshpass -p "{{ ansible_password }}" \
    ssh -T \
        -o StrictHostKeyChecking=no \
        -o UserKnownHostsFile=/dev/null \
        {{ ansible_user }}@{{ ansible_host }} << 'EOF'
    enable
    reload
    y
    reload
    y
    EOF
  async: 45
  poll: 0
  ignore_errors: true
  when:
    - stack.enabled
    - not stack_configured

- name: Pause briefly before polling for SSH (master only)
  pause:
    seconds: 30
  when:
    - stack.enabled
    - is_stack_master
    - not stack_configured

- name: Wait for master to come back after reload
  wait_for:
    host: "{{ ansible_host }}"
    port: 22
    timeout: 30
    delay: 5
  delegate_to: localhost
  retries: 20
  register: wait_result
  until: wait_result is succeeded
  when:
    - stack.enabled
    - is_stack_master
    - not stack_configured


# --------------------------------------------------
# VALIDATE STACK
# --------------------------------------------------
- name: Verify stack after reboot
  ansible.builtin.shell: |
    sshpass -p "{{ vault_switch_password }}" \
    ssh -tt \
    -o StrictHostKeyChecking=no \
    -o UserKnownHostsFile=/dev/null \
    -o PreferredAuthentications=password \
    -o PubkeyAuthentication=no \
    {{ ansible_user }}@{{ ansible_host }} << 'EOF'
    enable
    configure
    show stack-status
    port-channel auto
    exit
    exit
    EOF
  args:
    executable: /bin/bash

  register: stack_verify
  changed_when: false
  when:
    - stack.enabled
    - is_stack_master

- name: Print stack status
  debug:
    var: stack_verify.stdout
  when:
    - stack.enabled
    - is_stack_master

