- name: Validate application version
  fail:
    msg: >
      Application {{ application.name }} version mismatch.
      Expected {{ application.expected_version }},
      Found {{ netgear_app_version }}.
  when:
    - netgear_app_version != application.expected_version

- name: Application version validation passed
  debug:
    msg: >
      Application {{ application.name }} version validated successfully
      ({{ netgear_app_version }}).
