---
###############################################################################
# CORE SWITCH CONFIGURATION
###############################################################################

- name: Configure CORE switches (L2/L3, routing, services)
  hosts: core_switches
  gather_facts: no
  connection: local

  vars_files:
    - ../group_vars/core_switches/main.yml
    - ../group_vars/core_switches/vault.yml

  roles:

    - role: vlan
      when: vlans is defined

    - role: lag
      when: lags is defined

    - role: interface
      when: interfaces is defined

    - role: svi
      when: svis is defined

    - role: ospf
      when: routing.ospf is defined
